CREATE TABLE IF NOT EXISTS teste (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS teste;

CREATE TABLE IF NOT EXISTS teste (
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (cpf)
);

INSERT INTO teste (cpf,nome,created_at)
VALUES ('33855476982','João Almeida','2021-06-29');

INSERT INTO teste (cpf,nome,created_at)
VALUES ('33855476982','João Almeida','2021-06-29') ON CONFLICT (cpf) DO NOTHING;

UPDATE teste SET nome = 'Camila Vidal' WHERE cpf = '33855476982';

SELECT * FROM teste;